### ISSUE TITLE
"Docker Compose" instructions have no context

### ISSUE THREAD

**Issue by stone212** [postfixadmin/docker#11]
The Readme.md file says

```
Docker Compose

Try something like the below; changing the usernames/passwords as required.
```

But it does not say where you would "try something like the below".  What is this section talking about at all?

**Comment by DavidGoodwin** [comment]
If you were familiar with docker compose, you'd know the text provided was for a docker-compose.yml file  ....  I'll update the README.md a bit more! :)

**Comment by stone212** [comment]
@DavidGoodwin 
> If you were familiar with docker compose, you'd know the text provided was for a docker-compose.yml file

Probably that's true.  But I'm not familiar with docker compose.  Do I need to be?  In the instructions I don't see an answer.  You said "Try something like the below in a docker-compose.yml file; changing the usernames/passwords as required."  Because those are on the main/Readme/instructions/HowTo page it seems like that is mandatory.  But that can't be, can it?  Are you saying "if you want to use docker compose here are some hints?"

**Comment by DavidGoodwin** [comment]
Yes, it is trying to say " if you want to use docker compose, here are some hints " ....

**Comment by DavidGoodwin** [comment]
Docker compose allows you to orchestrate a number of containers - without you needing to type in a load of docker run commands. So ... if you didn't have any existing postfixadmin "infrastructure" (database server, web server) then using the docker compose stuff ought to be appealing (it provides a quick way to test out the software).

You don't need to use docker compose - you could just run the appropriate docker containers manually.
