### ISSUE TITLE
postfixadmin not found

### ISSUE THREAD

**Issue by stone212** [postfixadmin/docker#12]
I created a `config.local.php` and run this like this:

`docker run --name postfixadmin -p 8080:80 postfixadmin-image`

When I do it it completes without error but only the apache test config comes up in a browser.  I see this from the output:

```
+ echo 'Postfixadmin not found in /var/www/html - copying now...'
Postfixadmin not found in /var/www/html - copying now...
```

By "without error" I mean that it ends with this:

```
+ '[' -f upgrade.php ']'
+ exec php-fpm
[10-Jan-2019 04:49:21] NOTICE: fpm is running, pid 1
[10-Jan-2019 04:49:21] NOTICE: ready to handle connections

```

But `/var/www/html` does not contain anything but the apache test config.  Am I missing something?

**Comment by DavidGoodwin** [comment]
So, I'll try and not miss out any steps here so there's no chance for confusion.

I've just done a : 
``` git clone https://github.com/postfixadmin/docker.git docker && cd docker ```
```docker build --pull --rm -t postfixadmin-image apache```

This command spews out lots of text, but at the end you ought to see something like : 

```
Step 11/13 : COPY docker-entrypoint.sh /usr/local/bin/
 ---> Using cache
 ---> cbc51ba301b1
Step 12/13 : ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
 ---> Using cache
 ---> 0948fb73e1a6
Step 13/13 : CMD ["apache2-foreground"]
 ---> Using cache
 ---> da2db67a09d3
Successfully built da2db67a09d3
Successfully tagged postfixadmin-image:latest
```

If you now run this container with : 

```docker run --rm --name postfixadmin -p 8080:80 postfixadmin-image```

You should see something like the following : 

```
+ POSTFIXADMIN_DB_TYPE=sqlite
+ POSTFIXADMIN_DB_HOST=
+ POSTFIXADMIN_DB_USER=
+ POSTFIXADMIN_DB_PASSWORD=
+ POSTFIXADMIN_SETUP_PASSWORD=
+ [[ apache2-foreground == apache2* ]]
+ '[' -e index.php -a -e scripts/postfixadmin-cli.php ']'
+ echo 'Postfixadmin not found in /var/www/html - copying now...'
Postfixadmin not found in /var/www/html - copying now...
++ ls -A
+ '[' '' ']'
+ tar cf - --one-file-system -C /usr/src/postfixadmin .
+ tar xf -
+ echo 'Complete! Postfixadmin has been successfully copied to /var/www/html'
Complete! Postfixadmin has been successfully copied to /var/www/html
+ case "${POSTFIXADMIN_DB_TYPE}" in
+ '[' sqlite '!=' sqlite ']'
+ '[' sqlite = sqlite ']'
+ : /var/tmp/postfixadmin.db ....... 
```

Having a config.local.php in my current working directory (~/src/postfixadmin-stuff/docker) has no impact on the image, as the config.local.php file is not (yet) within the container.

If you want to use an existing config.local.php file, it'd need to be mounted into the container - so changing the run command to be something like this ought to work : 

```
docker run --rm --name postfixadmin -p 8080:80 -v $(pwd)/config.local.php:/var/www/html/config.local.php postfixadmin-image 
```


which will result in something like : 

```
docker run --rm --name postfixadmin -v $(pwd)/config.local.php:/var/www/html/config.local.php  -p 8080:80 postfixadmin-image 
+ POSTFIXADMIN_DB_TYPE=sqlite
+ POSTFIXADMIN_DB_HOST=
+ POSTFIXADMIN_DB_USER=
+ POSTFIXADMIN_DB_PASSWORD=
+ POSTFIXADMIN_SETUP_PASSWORD=
+ [[ apache2-foreground == apache2* ]]
+ '[' -e index.php -a -e scripts/postfixadmin-cli.php ']'
+ echo 'Postfixadmin not found in /var/www/html - copying now...'
Postfixadmin not found in /var/www/html - copying now...
++ ls -A
+ '[' config.local.php ']'
+ echo 'WARNING: /var/www/html is not empty - press Ctrl+C now if this is an error!'
WARNING: /var/www/html is not empty - press Ctrl+C now if this is an error!
+ set -x
+ ls -A
config.local.php
+ sleep 10
+ tar cf - --one-file-system -C /usr/src/postfixadmin .
+ tar xf -
+ echo 'Complete! Postfixadmin has been successfully copied to /var/www/html'
Complete! Postfixadmin has been successfully copied to /var/www/html
+ case "${POSTFIXADMIN_DB_TYPE}" in
+ '[' sqlite '!=' sqlite ']'
+ '[' sqlite = sqlite ']'
+ : /var/tmp/postfixadmin.db
+ '[' '!' -f /var/tmp/postfixadmin.db ']'
+ echo 'Creating sqlite db'
+ touch /var/tmp/postfixadmin.db
Creating sqlite db
+ chown www-data:www-data /var/tmp/postfixadmin.db
+ chmod 0700 /var/tmp/postfixadmin.db
+ '[' '!' -e config.local.php ']'
+ echo 'WARNING: /var/www/html/config.local.php already exists.'
+ echo 'Postfixadmin related environment variables have been ignored.'
+ '[' -f upgrade.php ']'
WARNING: /var/www/html/config.local.php already exists.
Postfixadmin related environment variables have been ignored. 
```

Once the container is running, you can rummage around inside it if you want by doing : 

```docker exec -ti postfixadmin /bin/bash```

Look in /var/www/html (```ls /var/www/html```) - note it takes a few seconds for the entrypoint script to run and install the software into there, so initially you may only see your config.local.php file - and then everything else will appear afterwards.

I'll update the docs with a hint of how to use an existing config.local.php file anyway.

**Comment by DavidGoodwin** [comment]
``` docker run --rm --name postfixadmin -d -v $(pwd)/config.local.php:/var/www/html/config.local.php  -p 8080:80 postfixadmin-image ```

Wait a few seconds ... and then try : 

```curl -XGET http://localhost:8080/````

and you should see this : 

```
<html>
    <head>
        <title>Welcome to Postfix Admin</title>
    </head>
    <body>
        <img id="login_header_logo" src="images/logo-default.png" />
        <h1>Welcome to Postfix Admin</h1>
        <h2>What is it?</h2> ......
```

**Comment by stone212** [comment]
@DavidGoodwin You posted two things.  The first says

> If you want to use an existing config.local.php file, it'd need to be mounted into the container

The Readme doesn't say this.  The other info you gave me about config.local.php didn't say this either.  Could you please please post complete info in the Readme?  So I will stop using config.local.php and try again.

one doesn't really relate to this Issue but the second one does.  You said `you should see this :`

I agree!  I should.  But I don't.  That's the Issue. :)  I just now stopped and removed the docker container and I re ran it using command line options for the DB.  It still says that postfixadmin is copied to /var/www/html *and nothing but the apache2 default config is ther* but running it this way causes another issue: https://github.com/postfixadmin/docker/issues/13

So first I am working on that one then I will come back to this.

**Comment by stone212** [comment]
> `docker run --rm --name postfixadmin -d -v $(pwd)/config.local.php:/var/www/html/config.local.php -p 8080:80 postfixadmin-imag`

This has a lot of new information that I do not understand so I am trying without config.local.php.  I don't want to make things more confusing than they have to be.  If I had a complete picture I am sure I could get this running in 10 minutes.

**Comment by J0WI** [comment]
Here you can find some general information about the concepts of Docker and how to deploy containers: https://docs.docker.com/get-started/

**Comment by stone212** [comment]
@J0WI Thank you but I don't see how that will help.  The issue here is the lack of install instructions, not Docker issues.  (Anyway I use Docker on 8 other production servers).

**Comment by DavidGoodwin** [comment]
> > `docker run --rm --name postfixadmin -d -v $(pwd)/config.local.php:/var/www/html/config.local.php -p 8080:80 postfixadmin-image`
> 
> This has a lot of new information that I do not understand so I am trying without config.local.php. I don't want to make things more confusing than they have to be. If I had a complete picture I am sure I could get this running in 10 minutes.


 * --rm - delete the container after it stops.
 * -d - run in the background/daemonise (do not hog the terminal)
 * -v foo:/something/bar - "mount" the file or directory 'foo' into the container at /something/bar
 * $(pwd) - shell command, will expand to your current working directory - e.g. /home/fred/src/postfixadmin/docker/
