### ISSUE TITLE
учтеная запись

### ISSUE THREAD

**Issue by dobry-kot** [postfixadmin/docker#17]
Добрый вечер. Какой логин и пароль от postfixAdmin https://localhost:8080?

**Comment by grikdotnet** [comment]
его надо настраивать, зайдя на http://example.com:8000/setup.php
это написано в документации

authors don't speak Russian, write in English

**Comment by DavidGoodwin** [comment]
Google translate gives me : "Good evening. What is the login and password from postfixAdmin https: // localhost: 8080?"

I'll improve the docs in a bit, but : 
 * You need to specify a POSTFIXADMIN_SETUP_PASSWORD env var to docker, and that needs to look a bit like : ``` a6844d6ce94f534dbd5736b0f9e1f884:2f442afdd7bc0018f2a0826cc3bdbadfbea7d4f5 ```
 * The easiest way to generate one of those is to run the container, and go to http://localhost:8080/setup.php and type something with at least 2 digits into the Setup Password box, at which point it'll echo out a generated value... then
 * Stop the container, and restart it with ```-e POSTFIXADMIN_SETUP_PASSWORD=a6844d6ce94f534dbd5736b0f9e1f884:2f442afdd7bc0018f2a0826cc3bdbadfbea7d4f5  ...... ``` 
 * Then visit http://localhost:8080/setup.php and you should now be able to add a new administrator.
 * Then visit http://localhost:8080 to login as that administrator

**Comment by DavidGoodwin** [comment]
Hi - try rebuilding the image now; I've updated the docs, and hard coded a default POSTFIXADMIN_SETUP_PASSWORD which is the equivalent of `topsecret99`
