### ISSUE TITLE
mips64le cannot work with current Dockerfiles (apache or fpm)

### ISSUE THREAD

**Issue by grooverdan** [postfixadmin/docker#45]
https://github.com/docker-library/official-images/blob/master/library/postfixadmin lists mips64le in the manifest.

This always fails
https://doi-janky.infosiftr.net/job/multiarch/job/mips64le/job/postfixadmin/

Always fails on mips64le because gosu isn't part of the debian repository for mips ref: https://packages.debian.org/buster/gosu

**Comment by grooverdan** [comment]
Of course with something [much more verbose](https://github.com/MariaDB/mariadb-docker/blob/9c83dce103302e80539ff2722db38a1be6ee4e6e/10.2/Dockerfile#L20-L41), https://github.com/tianon/gosu/releases has mips64el releases.

**Comment by J0WI** [comment]
The upgrade to Bullseye fix this: https://packages.debian.org/bullseye/gosu
