### ISSUE TITLE
Add variant with dovecot-core

### ISSUE THREAD

**Issue by Routhinator** [postfixadmin/docker#49]
Hi folks,

Would be nice to have a variant that contains dovecot-core (for debian)  so we have `doveadm` for ARGON2I passwords.

**Comment by DavidGoodwin** [comment]
@Routhinator - wait about a week or so and we'll have native support for ARGON2I passwords in postfixadmin - see https://github.com/postfixadmin/postfixadmin/pull/491

**Comment by DavidGoodwin** [comment]
I think this is no longer necessary - as postfixadmin/postfixadmin should support ARGON2I now.

**Comment by mtdcr** [comment]
Sorry for being late to the party! Could you possibly add a variant with dovecot-core to support `$CONF['encrypt'] = 'dovecot:SCRAM-SHA-1';` and possibly other algorithms?

According to https://github.com/postfixadmin/postfixadmin/issues/313 implementing SCRAM-SHA-* without doveadm is not planned, so installing dovecot-core by default seems sensible.
