### ISSUE TITLE
Encryption set to SHA512

### ISSUE THREAD

**Issue by domingo13** [postfixadmin/docker#62]
To make use of sha512 hashing of passwords, you need to provide the following setting:

`$CONF['encrypt'] = "php_crypt:SHA512::{SHA512-CRYPT}";`

if you have Dovecot as the backend, like this:

`default_pass_scheme = SHA512-CRYPT`

**Comment by qwc** [comment]
Fixing/mentioning that in the readme would be marvelous.

**Comment by DavidGoodwin** [comment]
Hm, there is this - https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/HASHING.md
 - but the version of postfixadmin used by this image is the 3.3 branch - so https://github.com/postfixadmin/postfixadmin/blob/postfixadmin_3.3/DOCUMENTS/HASHING.md is the correct file.


which does have this section - https://github.com/postfixadmin/postfixadmin/blob/postfixadmin_3.3/DOCUMENTS/HASHING.md#php_crypt

If you can suggest better wording, I'd love a PR or even just a paragraph of text I could paste in for you ...
