### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by zacekjakub** [postfixadmin/docker#68]
Hello,

the docker-compose makes no sense without definition of persitent-volumes. And because I have no specification of files used in container, I even can't manage to create the volumes myself.

**Comment by DavidGoodwin** [comment]
er, there isn't a docker-compose.yml file in this project....

**Comment by lordpayder** [comment]
https://github.com/postfixadmin/docker#docker-compose ?

**Comment by DavidGoodwin** [comment]
Sorry, I was just looking at files within the project! 

Persistent volume wise -

MySQL - handles that itself, I think, so I don't think anything is needed.

PostfixAdmin - it doesn't store anything important in local files (smarty might cache things etc but that's about it).

Is anything actually needed?

**Comment by zacekjakub** [comment]
Oh I got it now, I originally haven't got the point of this project and thought it hosts postfix and everything. Haven't realized it just manages the three MySQL tables.
