### ISSUE TITLE
Docker hub `postfixadmin-image` or just `postfixadmin`?

### ISSUE THREAD

**Issue by timbze** [postfixadmin/docker#69]
The README mentions `postfixadmin-image`, but that does not seem to work.

**Comment by fweep** [comment]
It's just `postfixadmin`. Use this one: https://hub.docker.com/_/postfixadmin.

**Comment by DavidGoodwin** [comment]
Thanks for noticing  -> i was building it locally at the time and tagging the image with 'postfixadmin-image' ...

Sorry! Hopefully fixed...
