### ISSUE TITLE
unable to prepare context

### ISSUE THREAD

**Issue by stone212** [postfixadmin/docker#8]
I installed docker CE using these instructions: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-debian-9

Then I followed the build instructions in the readme and I get this:

```
root@mail:/etc# docker build --pull --rm -t postfixadmin-image fpm-alpine
unable to prepare context: path "fpm-alpine" not found
root@mail:/etc# docker build --pull --rm -t postfixadmin-image fpm
unable to prepare context: path "fpm" not found

```

**Comment by stone212** [comment]
The problem is that the doc is really lazy here.  It should read:
```
Building:

1. $ git clone https://github.com/postfixadmin/docker.git

2. $ cd docker

3. $ docker build --pull --rm -t postfixadmin-image variant
```

The Readme skips steps 1 and 2.

**Comment by DavidGoodwin** [comment]
Sorry; steps 1 & 2 are kind of 'obvious' after you've been using github for a while .... I'll try and add something in to resolve this ...

**Comment by stone212** [comment]
@DavidGoodwin Everything is obvious when you already know what it is.

**Comment by DavidGoodwin** [comment]
Yeah I know ....  Thanks for reporting your findings !
