### ISSUE TITLE
"Running" instructions unclear

### ISSUE THREAD

**Issue by stone212** [postfixadmin/docker#9]
The Readme.md file says:

```
Running
No config.local.php / no existing setup

If you do not have a config.local.php
```

It does not say what a `config.local.php` file is, where it is located, why you would have it or anything else.  What is it talking about?

**Comment by stone212** [comment]
@DavidGoodwin 

> Rather than editing that file (which makes it difficult to update the code in the future) create a file called config.local.php.

Ah, you see?  *This* is helpful information that should probably be on the readme/howto page.  But you still haven't explained where this file should be.  In the "docker" directory?  Maybe your codebase should have a blank one by default?

Does having this file overwrite any other settings or do you have to explicitly state a setting in this file for it to overwrite the default?  Something else that could go on the readme.

**Comment by stone212** [comment]
@DavidGoodwin Okay testing reveals it belongs in the docker/ directory.  I beleive in making projects better but if this gets annoying I can do a fork and pull requests for new docs.  I still think it's better if the coder writes the doc always.

**Comment by DavidGoodwin** [comment]
config.local.php needs to exist in the same directory as postfixadmin's config.inc.php.

I think we don't create an  empty one if one doesn't exist, as the code tries to show an appropriate error message if it's missing.

(Don't worry about the bug requests; keep them coming ... )

**Comment by stone212** [comment]
@DavidGoodwin 

> config.local.php needs to exist in the same directory as postfixadmin's config.inc.php.

What do you mean `postfixadmin's config.inc.php`?  There is no place on the Readme that says anything about this.

**Comment by stone212** [comment]
@DavidGoodwin We are getting way off the topic and I feel like I am already working so hard to help you organize this that for me to do more is asking too much.  I will proofread the doc if you ask me to.  You can contact me here and I will see it.
